"use client";

import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { AlertCircle, CheckCircle2, Eye, FileText, FolderOpen, Loader2, RotateCcw, Search, ShieldCheck, Trash2, Upload, UserRound, X } from "lucide-react";
import Pagination from "@/components/Pagination";
import RoleGuard from "@/guards/RoleGuard";
import { useGetAllpatient } from "@/hooks/Patient/usePatientRegistration";
import { useDeletePatientChartAttachment, usePatientChartAttachments, useUploadPatientChartAttachment } from "@/hooks/Patient/usePatientCharts";
import { openPatientChartAttachment } from "@/services/patient-chart.services";
import { PatientChartAttachment } from "@/types/PatientChartTypes";
import { PatientProps } from "@/types/PatientTypes";
import { getApiErrorMessage } from "@/utils/api-error";
import { isSupportedPatientChartFile, patientChartFileAccept } from "@/utils/patient-chart-file";
import PatientChartBatchIntake from "@/components/PatientChart/PatientChartBatchIntake";

type QueueStatus = "pending" | "uploading" | "complete" | "uploadError" | "invalid";
type QueueItem = { id: string; file: File; progress: number; status: QueueStatus; error?: string };
type PendingDelete = PatientChartAttachment & { deleteError?: string };

const MAX_FILE_SIZE = 10 * 1024 * 1024;
const PATIENT_PAGE_SIZE = 12;
const DOCUMENT_PAGE_SIZE = 8;
let queueItemSequence = 0;

const formatBytes = (bytes: number) => bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`;
const formatDate = (value: string) => new Date(value).toLocaleString("en-PH", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" });
const createQueueItem = (file: File): QueueItem => {
  const error = !isSupportedPatientChartFile(file) ? "Only PDF, JPG, and PNG files are accepted." : file.size > MAX_FILE_SIZE ? "File exceeds the 10 MB limit." : undefined;
  queueItemSequence += 1;
  return { id: `chart-${Date.now()}-${file.lastModified}-${queueItemSequence}`, file, progress: 0, status: error ? "invalid" : "pending", error };
};

function ChartFileRow({ attachment, onDelete }: { attachment: PatientChartAttachment; onDelete: (attachment: PatientChartAttachment) => void }) {
  return <article className="grid gap-3 border-b border-[#e5ebf1] px-4 py-4 last:border-b-0 md:grid-cols-[minmax(0,1fr)_120px_168px_auto] md:items-center md:px-5">
    <div className="flex min-w-0 items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-[#e8f5f4] text-[#0e7c7b]"><FileText size={19} /></span><div className="min-w-0"><p className="truncate text-sm font-semibold text-[#183252]" title={attachment.file_name}>{attachment.file_name}</p><p className="mt-0.5 text-xs text-[#6c7f93]">{attachment.mime_type === "application/pdf" ? "PDF document" : "Scanned image"} · {formatBytes(attachment.file_size)}</p></div></div>
    <p className="text-xs font-medium text-[#456279]">{attachment.uploader?.name ?? "System"}</p><p className="text-xs text-[#6c7f93]">{formatDate(attachment.created_at)}</p>
    <div className="flex gap-2 md:justify-end"><button type="button" onClick={() => openPatientChartAttachment(attachment.attachment_id)} className="inline-flex items-center gap-1.5 rounded-md border border-[#d4e0ea] bg-white px-2.5 py-2 text-xs font-semibold text-[#173b63] hover:bg-[#f5f8fb]"><Eye size={14} /> View</button><button type="button" onClick={() => onDelete(attachment)} className="inline-flex items-center gap-1.5 rounded-md border border-[#f0d3d0] bg-[#fff8f7] px-2.5 py-2 text-xs font-semibold text-[#ae3f35] hover:bg-[#fce9e7]"><Trash2 size={14} /> Delete</button></div>
  </article>;
}

function UploadQueueRow({ item, isUploading, onRemove, onReplace, onRetry }: { item: QueueItem; isUploading: boolean; onRemove: () => void; onReplace: (files: FileList | null) => void; onRetry: () => void }) {
  return <article className={`rounded-lg border p-3 ${item.status === "invalid" ? "border-[#efd6a3] bg-[#fffaf0]" : item.status === "uploadError" ? "border-[#f1cfca] bg-[#fffafa]" : "border-[#dce5ed]"}`}>
    <div className="flex gap-3"><FileText size={19} className="mt-0.5 shrink-0 text-[#4f6885]"/><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><p className="truncate text-sm font-medium">{item.file.name}</p><p className="text-xs text-[#74859a]">{formatBytes(item.file.size)}</p></div><span className="flex items-center gap-2">{item.status === "complete" ? <CheckCircle2 size={18} className="text-[#11816f]"/> : item.status === "invalid" || item.status === "uploadError" ? <AlertCircle size={18} className="text-[#c65b37]"/> : null}<button type="button" onClick={onRemove} disabled={isUploading} aria-label={`Remove ${item.file.name}`} className="text-[#74859a] hover:text-[#b44635] disabled:opacity-50"><X size={17}/></button></span></div>
      {item.status === "uploading" && <div className="mt-2 h-1.5 overflow-hidden rounded bg-[#dbe8e8]"><div className="h-full bg-[#0e7c7b] transition-all" style={{ width: `${item.progress}%` }}/></div>}
      {item.status === "uploadError" && <div className="mt-2 flex items-center justify-between gap-2"><p className="text-xs text-[#b44635]">{item.error}</p><button type="button" onClick={onRetry} disabled={isUploading} className="inline-flex items-center gap-1 text-xs font-semibold text-[#0e6b6a]"><RotateCcw size={13}/> Retry</button></div>}
      {item.status === "invalid" && <div className="mt-2 flex items-center justify-between gap-2"><p className="text-xs text-[#9a6717]">{item.error}</p><label className="cursor-pointer text-xs font-semibold text-[#0e6b6a]">Replace<input type="file" accept={patientChartFileAccept} className="sr-only" onChange={(event) => { onReplace(event.target.files); event.target.value = ""; }}/></label></div>}
      {item.status === "pending" && <p className="mt-2 text-xs font-medium text-[#a06810]">Ready to upload</p>}{item.status === "complete" && <p className="mt-2 text-xs font-medium text-[#11816f]">Filed in this patient’s chart</p>}
    </div></div>
  </article>;
}

export default function PatientChartsPage() {
  const [search, setSearch] = useState("");
  const [patientPage, setPatientPage] = useState(1);
  const [documentPage, setDocumentPage] = useState(1);
  const [selectedPatient, setSelectedPatient] = useState<PatientProps | null>(null);
  const [queue, setQueue] = useState<QueueItem[]>([]);
  const [attachmentToDelete, setAttachmentToDelete] = useState<PendingDelete | null>(null);
  const activeUploadIds = useRef(new Set<string>());
  const { data: patientResponse, isLoading: isPatientsLoading, error: patientError } = useGetAllpatient(search, patientPage, PATIENT_PAGE_SIZE);
  const { data: documentResponse, isLoading: isDocumentsLoading, error: documentError } = usePatientChartAttachments(selectedPatient?.patient_id, documentPage, DOCUMENT_PAGE_SIZE);
  const { mutateAsync: upload } = useUploadPatientChartAttachment();
  const { mutateAsync: deleteAttachment, isPending: isDeleting } = useDeletePatientChartAttachment();
  const patients = patientResponse?.data ?? [];
  const patientPagination = patientResponse?.pagination;
  const documents = documentResponse?.data ?? [];
  const documentPagination = documentResponse?.pagination;
  const isUploading = queue.some((item) => item.status === "uploading");
  const queueCounts = useMemo(() => ({ complete: queue.filter((item) => item.status === "complete").length, invalid: queue.filter((item) => item.status === "invalid").length, ready: queue.filter((item) => item.status === "pending" || item.status === "uploadError").length, size: queue.reduce((sum, item) => sum + item.file.size, 0) }), [queue]);

  useEffect(() => { setPatientPage(1); }, [search]);
  useEffect(() => { setDocumentPage(1); }, [selectedPatient?.patient_id]);
  const selectPatient = (patient: PatientProps) => { setSelectedPatient(patient); setQueue([]); };
  const addFiles = (files: FileList | null) => { if (files) setQueue((current) => [...current, ...Array.from(files).map(createQueueItem)]); };
  const replaceFile = (id: string, files: FileList | null) => { const file = files?.[0]; if (file) setQueue((current) => current.map((item) => item.id === id ? { ...createQueueItem(file), id } : item)); };
  const removeFile = (id: string) => setQueue((current) => current.filter((item) => item.id !== id));
  const uploadItem = async (item: QueueItem) => {
    if (!selectedPatient || item.status === "invalid" || item.status === "complete" || activeUploadIds.current.has(item.id)) return;
    activeUploadIds.current.add(item.id);
    setQueue((current) => current.map((entry) => entry.id === item.id ? { ...entry, status: "uploading", progress: 0, error: undefined } : entry));
    try {
      await upload({ file: item.file, patientId: selectedPatient.patient_id!, onProgress: (progress) => setQueue((current) => current.map((entry) => entry.id === item.id ? { ...entry, progress } : entry)) });
      setQueue((current) => current.map((entry) => entry.id === item.id ? { ...entry, status: "complete", progress: 100 } : entry));
    } catch (error) { setQueue((current) => current.map((entry) => entry.id === item.id ? { ...entry, status: "uploadError", error: getApiErrorMessage(error, "Upload failed. Check your connection and retry this file.") } : entry)); }
    finally { activeUploadIds.current.delete(item.id); }
  };
  const uploadAll = async () => { if (!selectedPatient || isUploading) return; for (const item of queue.filter((entry) => entry.status === "pending" || entry.status === "uploadError")) await uploadItem(item); };
  const confirmDelete = async () => {
    if (!attachmentToDelete) return;
    try { await deleteAttachment(attachmentToDelete.attachment_id); setAttachmentToDelete(null); if (documents.length === 1 && documentPage > 1) setDocumentPage((page) => page - 1); }
    catch (error) { setAttachmentToDelete((current) => current ? { ...current, deleteError: getApiErrorMessage(error, "Unable to delete this file.") } : current); }
  };

  return <RoleGuard allowedRoles={["ADMIN"]}><main className="min-h-screen bg-[#f3f6f9] font-['DM_Sans'] text-[#172a46]">
    <header className="border-b border-[#2a5579] bg-[#102b4e] px-5 py-6 md:px-9"><p className="text-[10px] font-bold uppercase tracking-[0.24em] text-[#86ded5]">Clinical records · chart control desk</p><div className="mt-1 flex flex-wrap items-end justify-between gap-5"><div><h1 className="font-['DM_Serif_Display'] text-3xl text-white">Patient chart management</h1><p className="mt-1 text-sm text-[#c3d2df]">File, review, and safely maintain each patient’s private scanned medical chart.</p></div><div className="grid min-w-[245px] grid-cols-2 gap-px overflow-hidden rounded-lg border border-[#477493] bg-[#477493] text-xs shadow-inner"><div className="bg-[#173b63] px-3 py-2.5"><p className="uppercase tracking-wider text-[#9bbdce]">Selected chart</p><p className="mt-1 truncate font-semibold text-white">{selectedPatient ? `${selectedPatient.patient_code ?? "No code"} · ${selectedPatient.name}` : "Not selected"}</p></div><div className="bg-[#173b63] px-3 py-2.5"><p className="uppercase tracking-wider text-[#9bbdce]">Documents</p><p className="mt-1 font-semibold text-white">{documentPagination?.total ?? 0} filed · {queueCounts.ready} ready</p></div></div></div></header>
    <div className="mx-auto grid max-w-7xl gap-6 p-5 lg:grid-cols-[minmax(300px,0.72fr)_minmax(0,1.5fr)] lg:p-8">
      <aside className="h-fit overflow-hidden rounded-xl border border-[#d6e0ea] bg-white shadow-sm"><div className="border-b border-[#e4ebf1] p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">1. Find a patient</h2><span className="text-xs text-[#60748d]">{patientPagination?.total ?? 0} records</span></div><label className="relative mt-3 block"><Search className="absolute left-3 top-3 text-[#60748d]" size={16}/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Name or patient code" className="w-full rounded-lg border border-[#cdd9e5] py-2.5 pl-9 pr-3 text-sm outline-none focus:border-[#0e7c7b]" /></label><p className="mt-2 text-xs text-[#6f8297]">Search is performed by the patient directory. Select one chart to manage its files.</p></div><div className="max-h-[480px] overflow-y-auto p-3">{isPatientsLoading ? <p className="p-4 text-sm text-slate-500">Loading patients…</p> : patientError ? <p className="p-4 text-sm text-red-700">{getApiErrorMessage(patientError, "Unable to load patients.")}</p> : patients.length === 0 ? <p className="p-4 text-sm text-slate-500">No matching patients found.</p> : patients.map((patient) => <button key={patient.patient_id} type="button" onClick={() => selectPatient(patient)} className={`mb-2 flex w-full items-center gap-3 rounded-lg border p-3 text-left transition ${selectedPatient?.patient_id === patient.patient_id ? "border-[#0e7c7b] bg-[#e9f7f6] shadow-[inset_3px_0_0_#0e7c7b]" : "border-transparent hover:border-[#d7e1ea] hover:bg-[#f7fafc]"}`}><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#eaf0f7] text-sm font-bold text-[#173b63]">{patient.name.split(" ").map((part) => part[0]).slice(0, 2).join("")}</span><span className="min-w-0"><span className="block truncate text-sm font-semibold">{patient.name}</span><span className="block text-xs text-[#60748d]">{patient.patient_code ?? "No code"} · {patient.age ?? "—"} yrs</span></span></button>)}</div>{patientPagination && patientPagination.totalPages > 1 && <Pagination currentPage={patientPage} totalPages={patientPagination.totalPages} totalEntries={patientPagination.total} calculateStartIndex={() => patientPagination.total ? (patientPage - 1) * PATIENT_PAGE_SIZE + 1 : 0} calculateEndIndex={() => Math.min(patientPage * PATIENT_PAGE_SIZE, patientPagination.total)} setCurrentPage={setPatientPage} />}</aside>
      <section className="space-y-6"><PatientChartBatchIntake /><section className="overflow-hidden rounded-xl border border-[#d6e0ea] bg-white shadow-sm"><div className="border-b border-[#e4ebf1] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#0e7c7b]">Private patient chart</p><h2 className="mt-1 text-lg font-semibold">2. Document intake</h2></div><ShieldCheck size={20} className="text-[#0e7c7b]" /></div>{selectedPatient ? <div className="mt-4 flex items-center gap-3 border-l-4 border-[#0e7c7b] bg-[#eff7f7] p-3"><UserRound size={18} className="text-[#0e7c7b]"/><div><p className="text-sm font-semibold">{selectedPatient.name}</p><p className="text-xs text-[#527083]">{selectedPatient.patient_code ?? "No patient code"} · {documentPagination?.total ?? 0} filed documents</p></div></div> : <p className="mt-3 text-sm text-[#60748d]">Select a patient before adding a scanned record.</p>}</div><div className="p-5"><label className={`flex flex-col items-center justify-center rounded-lg border border-dashed p-7 text-center ${selectedPatient ? "cursor-pointer border-[#78aaa7] bg-[#f3fbfa] hover:bg-[#eaf7f5]" : "cursor-not-allowed border-[#d7e0e7] bg-[#f8fafb]"}`}><Upload className="text-[#0e7c7b]" size={24}/><span className="mt-2 text-sm font-semibold">Choose scanned journal files</span><span className="mt-1 text-xs text-[#60748d]">PDF, JPG, or PNG · up to 10 MB each · review the queue before uploading</span><input disabled={!selectedPatient || isUploading} type="file" multiple accept={patientChartFileAccept} className="sr-only" onChange={(event: ChangeEvent<HTMLInputElement>) => { addFiles(event.target.files); event.target.value = ""; }} /></label>{queue.length > 0 && <div className="mt-5 space-y-2">{queue.map((item) => <UploadQueueRow key={item.id} item={item} isUploading={isUploading} onRemove={() => removeFile(item.id)} onReplace={(files) => replaceFile(item.id, files)} onRetry={() => uploadItem(item)} />)}</div>}<div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-[#e4ebf1] pt-4"><p className="text-xs text-[#60748d]">{queueCounts.complete} filed · {queueCounts.ready} ready · {queueCounts.invalid} blocked · {formatBytes(queueCounts.size)} selected</p><button type="button" onClick={uploadAll} disabled={!selectedPatient || queueCounts.ready === 0 || isUploading} className="inline-flex items-center gap-2 rounded-lg bg-[#0e7c7b] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#096968] disabled:cursor-not-allowed disabled:opacity-50"><Upload size={16}/>{isUploading ? "Uploading…" : "Upload eligible files"}</button></div></div></section>
        <section className="overflow-hidden rounded-xl border border-[#d6e0ea] bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#e4ebf1] px-5 py-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#edf2f8] text-[#173b63]"><FolderOpen size={18}/></span><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#0e7c7b]">Filed documents</p><h2 className="text-base font-semibold">3. Chart file library</h2></div></div><span className="text-xs font-medium text-[#60748d]">{documentPagination?.total ?? 0} total</span></div>{!selectedPatient ? <div className="flex min-h-52 flex-col items-center justify-center px-5 text-center"><FolderOpen size={28} className="text-[#9aabba]"/><p className="mt-3 text-sm font-semibold text-[#455f76]">Choose a patient to open their document library.</p><p className="mt-1 text-xs text-[#778a9d]">Stored files stay grouped under the selected patient’s chart.</p></div> : isDocumentsLoading ? <div className="flex min-h-52 items-center justify-center gap-2 text-sm text-[#60748d]"><Loader2 size={18} className="animate-spin"/> Loading chart documents…</div> : documentError ? <div className="min-h-52 p-5 text-sm text-[#b44635]">{getApiErrorMessage(documentError, "Unable to load this patient’s chart files.")}</div> : documents.length === 0 ? <div className="flex min-h-52 flex-col items-center justify-center px-5 text-center"><FileText size={28} className="text-[#9aabba]"/><p className="mt-3 text-sm font-semibold text-[#455f76]">No chart documents filed yet.</p><p className="mt-1 text-xs text-[#778a9d]">Use the intake panel above to add the first scanned record.</p></div> : <><div className="hidden grid-cols-[minmax(0,1fr)_120px_168px_auto] gap-3 border-b border-[#e5ebf1] bg-[#f8fafc] px-5 py-2.5 text-[10px] font-bold uppercase tracking-[0.14em] text-[#75879a] md:grid"><span>Document</span><span>Filed by</span><span>Added</span><span className="text-right">Actions</span></div>{documents.map((attachment) => <ChartFileRow key={attachment.attachment_id} attachment={attachment} onDelete={setAttachmentToDelete} />)}</>}{selectedPatient && documentPagination && documentPagination.totalPages > 1 && <Pagination currentPage={documentPage} totalPages={documentPagination.totalPages} totalEntries={documentPagination.total} calculateStartIndex={() => documentPagination.total ? (documentPage - 1) * DOCUMENT_PAGE_SIZE + 1 : 0} calculateEndIndex={() => Math.min(documentPage * DOCUMENT_PAGE_SIZE, documentPagination.total)} setCurrentPage={setDocumentPage} />}</section></section>
    </div>
    {attachmentToDelete && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#07182e]/45 p-5" role="dialog" aria-modal="true" aria-labelledby="delete-chart-title"><div className="w-full max-w-md rounded-xl bg-white p-6 shadow-2xl"><div className="flex h-11 w-11 items-center justify-center rounded-lg bg-[#fff0ee] text-[#b44635]"><Trash2 size={20}/></div><h2 id="delete-chart-title" className="mt-4 text-lg font-semibold text-[#183252]">Delete chart document?</h2><p className="mt-2 text-sm text-[#60748d]">This permanently removes <span className="font-semibold text-[#38546f]">{attachmentToDelete.file_name}</span> from this patient’s private chart. This cannot be undone.</p>{attachmentToDelete.deleteError && <p className="mt-3 rounded-md bg-[#fff3f1] p-2 text-xs text-[#b44635]">{attachmentToDelete.deleteError}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setAttachmentToDelete(null)} disabled={isDeleting} className="rounded-lg border border-[#d4e0ea] px-4 py-2 text-sm font-semibold text-[#38546f] hover:bg-[#f5f8fb]">Cancel</button><button type="button" onClick={confirmDelete} disabled={isDeleting} className="inline-flex items-center gap-2 rounded-lg bg-[#b44635] px-4 py-2 text-sm font-semibold text-white hover:bg-[#96372c] disabled:opacity-60">{isDeleting && <Loader2 size={15} className="animate-spin"/>} Delete file</button></div></div></div>}
  </main></RoleGuard>;
}
