import { PrismaClient } from "@prisma/client";

export async function seedServices(prisma: PrismaClient) {

    // Clear existing seeded data
    await prisma.services.deleteMany();
    await prisma.services.deleteMany();
    await prisma.services.deleteMany();


    await prisma.services.createMany({
        data: [
            {
                reference_id: 1,
                service_name: 'FBS',
                price: 120,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 2,
                service_name: 'Random Blood Sugar',
                price: 150,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 3,
                service_name: 'Urea (BUN)',
                price: 180,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 4,
                service_name: 'Creatinine',
                price: 200,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 5,
                service_name: 'Blood Chemistry',
                price: 350,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 6,
                service_name: 'Uric Acid',
                price: 160,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 7,
                service_name: 'Total Cholesterol',
                price: 220,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 8,
                service_name: 'HDL-Cholesterol',
                price: 250,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 9,
                service_name: 'LDL-Cholesterol',
                price: 250,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 10,
                service_name: 'Triglycerides',
                price: 230,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 11,
                service_name: '1H-OGTT',
                price: 300,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 12,
                service_name: '2H-OGTT',
                price: 320,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 13,
                service_name: 'OGTT 75G',
                price: 350,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 32,
                service_name: '2H-OGTT Gestational',
                price: 320,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 14,
                service_name: 'OGTT',
                price: 280,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 15,
                service_name: 'Serum Glutamic Pyruvic Transaminase',
                price: 260,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 16,
                service_name: 'Sodium',
                price: 180,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 17,
                service_name: 'Potassium',
                price: 180,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 18,
                service_name: 'Ionized Calcium',
                price: 450,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 19,
                service_name: 'HbA1c',
                price: 500,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 20,
                service_name: 'Urinalysis',
                price: 120,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 21,
                service_name: 'Fecalysis',
                price: 130,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 22,
                service_name: 'Fecal Occult Blood Test',
                price: 250,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 23,
                service_name: 'Pregnancy Test (Urine)',
                price: 180,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 24,
                service_name: 'Pregnancy Test (Serum)',
                price: 250,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 25,
                service_name: 'Dengue NS1',
                price: 650,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 26,
                service_name: 'Syphilis',
                price: 300,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 27,
                service_name: 'Hepatitis B Surface Antigen',
                price: 450,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 28,
                service_name: 'Complete Blood Count with Platelet Count',
                price: 250,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 29,
                service_name: 'CBC',
                price: 200,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 30,
                service_name: 'Blood Typing',
                price: 180,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 31,
                service_name: "Ionized Calcium",
                price: 500,
                category: "LABORATORY",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 31,
                service_name: 'Consultation',
                price: 1000,
                category: "CONSULTATION",
                date: new Date(),
                created_at: new Date(),
            },
            {
                reference_id: 32,
                service_name: 'Medical Certificate',
                price: 500,
                category: "CERTIFICATE",
                date: new Date(),
                created_at: new Date(),
            },
        ],
        skipDuplicates: true,
    });
}
